
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-organic-w24-6pm-3
owner: ucsb-cs156-w24
repo_name: proj-organic-w24-6pm-3
pull_requests: [{"author":{"id":"U_kgDOBX3m_g","is_bot":false,"login":"welaalice","name":"Towela Phiri"},"headRefName":"TP-JoinButton","number":38,"title":"TP - Added Join Button","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-3/pull/38"},{"author":{"id":"U_kgDOB3D_OQ","is_bot":false,"login":"kenisha-v","name":"Kenisha Vaswani"},"headRefName":"kv-bugs","number":37,"title":"KV - BUG Courses Start Date cannot be before the End date","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-3/pull/37"},{"author":{"id":"U_kgDOB3CMjQ","is_bot":false,"login":"jenniferlopez17","name":""},"headRefName":"JL-adminRights","number":36,"title":"JL - Bug Admin can Toggle Their Admin Rights Of","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-3/pull/36"},{"author":{"id":"MDQ6VXNlcjg2NzQzODY1","is_bot":false,"login":"Jenniebn","name":"Jennie Wu"},"headRefName":"JW-iconbug","number":35,"title":"Jw iconbug","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-3/pull/35"}]
